import os, re

BASE = r'D:\web\portfolio entrepreneur'

# 1. Certifications Modal Removal
path_certs = os.path.join(BASE, 'certifications.html')
with open(path_certs, 'r', encoding='utf-8') as f:
    certs = f.read()

# Change how cards are rendered in rebuild_certs.py or in the HTML directly
# The HTML generates the grid dynamically. I need to modify rebuild_certs.py
path_rebuild = os.path.join(BASE, 'rebuild_certs.py')
if os.path.exists(path_rebuild):
    with open(path_rebuild, 'r', encoding='utf-8') as f:
        rebuild_script = f.read()
    
    # In rebuild_certs.py, the card is generated with onclick="openD(${i})"
    # Let's change it to href="${c.pdf || '#'}" target="_blank" and remove onclick
    rebuild_script = rebuild_script.replace(
        'onclick="openD(${i})"',
        'href="${c.pdf || \'#\'}" target="_blank"'
    )
    with open(path_rebuild, 'w', encoding='utf-8') as f:
        f.write(rebuild_script)
    
    # Run the rebuild script to regenerate certifications.html
    import subprocess
    subprocess.run(['python', 'rebuild_certs.py'], cwd=BASE)

# Also fix certifications.html directly if it has hardcoded grid (it was generated by JS inside it actually!)
# Let's check certifications.html
with open(path_certs, 'r', encoding='utf-8') as f:
    certs = f.read()
# Replace onclick="openD(${i})" in the render logic
certs = certs.replace('onclick="openD(${i})"', 'href="${c.pdf || \'#\'}" target="_blank"')
# Remove cursor:pointer and make it an anchor tag if it wasn't
certs = certs.replace('<div class="cert-card reveal"', '<a class="cert-card reveal" style="text-decoration:none;color:inherit;"')
certs = certs.replace('</div>\n    </div>\n  </div>', '</div>\n    </div>\n  </a>')

with open(path_certs, 'w', encoding='utf-8') as f:
    f.write(certs)


# 2. Hero Black Box completely remove
path_index = os.path.join(BASE, 'index.html')
with open(path_index, 'r', encoding='utf-8') as f:
    index = f.read()

# Remove the hero-photo-card completely
index = re.sub(
    r'<div class="hero-photo-card".*?>.*?</div>\s*</div>',
    '</div>',
    index,
    flags=re.DOTALL
)

# 3. Awards Grid explicitly fix gap
# Right column container has grid-template-rows:1fr 1fr;
# A tags have height:100%;
# Let's change the A tags to explicit height: 150px
index = index.replace(
    'style="text-decoration:none;display:block;position:relative;border-radius:1.25rem;overflow:hidden;border:1px solid rgba(255,255,255,.1);background:#0a0a12;height:100%;"',
    'style="text-decoration:none;display:block;position:relative;border-radius:1.25rem;overflow:hidden;border:1px solid rgba(255,255,255,.1);background:#0a0a12;height:150px;"'
)
# And make the left card explicitly 320px (it already is)
# And the container align-items: stretch
index = index.replace(
    'style="display:grid;grid-template-columns:1.4fr 1fr;gap:1.25rem;margin-bottom:1.25rem;"',
    'style="display:grid;grid-template-columns:1.4fr 1fr;gap:1.25rem;margin-bottom:1.25rem;align-items:stretch;"'
)

with open(path_index, 'w', encoding='utf-8') as f:
    f.write(index)

# 4. Garnet and Unbounded card images filling
path_blog = os.path.join(BASE, 'blog.html')
with open(path_blog, 'r', encoding='utf-8') as f:
    blog = f.read()

# Replace Garnet img styling
blog = re.sub(
    r'<img src="assets/logo/garnet/garnet.png" alt="Garnet" style="object-fit:contain;background:#fff;padding:1\.5rem;">',
    r'<img src="assets/logo/garnet/garnet.png" alt="Garnet" style="width:100%;height:100%;object-fit:cover;border-radius:0;">',
    blog
)
# Replace Unbounded img styling
blog = re.sub(
    r'<img src="assets/logo/unbounded/unbounded logo.jpg" alt="Unbounded" style="object-fit:cover;">',
    r'<img src="assets/logo/unbounded/unbounded logo.jpg" alt="Unbounded" style="width:100%;height:100%;object-fit:cover;border-radius:0;">',
    blog
)

# 5. Add Riadi card to blog grid
riadi_card = """
    <a href="article-riadi.html" class="card reveal" data-cat="Entrepreneurship & Sports Tech" data-url="article-riadi.html">
      <div class="card-img">
        <img src="assets/marwan_images/Accelerator Program at Flat6Labs/Selected for the Accelerator Program at Flat6Labs.jpeg" alt="Riadi: Building the Future of Sports Tech" style="width:100%;height:100%;object-fit:cover;">
        <span class="card-cat">🚀 Entrepreneurship & Sports Tech</span>
      </div>
      <div class="card-body">
        <h3 class="card-title">Riadi: Digitizing Athletic Performance</h3>
        <p class="card-desc">The complete journey of building a premier sports-tech ecosystem across the Arab world.</p>
        <div class="card-footer">
          <div class="card-author">
            <img src="assets/marwan_images/personal/main image.png" alt="Marwan" class="card-avatar">
            <span class="card-name">Marwan · 2026</span>
          </div>
          <button class="card-share" title="Share" onclick="event.preventDefault();event.stopPropagation();sharePost('article-riadi.html')">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
          </button>
        </div>
      </div>
    </a>
"""

if 'Riadi: Digitizing Athletic Performance' not in blog:
    # Insert at the beginning of the articles-grid
    blog = blog.replace('<div class="articles-grid" id="articles-grid">\n', '<div class="articles-grid" id="articles-grid">\n' + riadi_card)

with open(path_blog, 'w', encoding='utf-8') as f:
    f.write(blog)

print("Final fixes applied successfully.")
